namespace Game.Server.Packets
{
	public enum HorseRacePackageType
	{
		HORSERACE_OPEN_CLOSE = 160,
		HORSERACE_INITPLAYER = 1,
		HORSERACE_UPDATECOUNT = 2,
		HORSERACE_PLAYERSPEED_CHANGE = 9,
		HORSERACE_RACE_END = 10,
		HORSERACE_START_FIVE = 3,
		HORSERACE_BEGIN_RACE = 4,
		HORSERACE_BUFF_FLUSH = 8,
		HORSERACE_BUFF_ITEMFLUSH = 7,
		HORSERACE_ALLPLAYER_RACEEND = 6,
		HORSERACE_SYN_ONESECOND = 5,
		HORSERACE_SHOW_MSG = 11
	}
}
